version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: false  # We're not using Sphinx

mkdocs:
  configuration: mkdocs.yml  # Name of your config file

python:
  install:
    - requirements: docs/requirements.txt
