site_name: REViiT

nav:
  - Home: index.md

  - User Authentication:
      - Login: login.md
      - Signup: signup.md

  - Notes & Flashcards:
      - Notes Feature: notes.md
      - Flashcards Feature: flashcards.md

  - Leaderboards: leaderboard.md

  - Backend & Database:
      - Database Tables: database.md

  - Project Details:
      - Testing: testing.md
      - Contribution Guide: contribution.md

theme:
  name: mkdocs